# Multiple notifications bug: https://github.com/argoproj-labs/argocd-notifications/issues/90
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    myUsername: "Jane Doe" # ADD HERE YOUR USERNAME
  service.webhook.webhook-site: |
    url: "https://webhook.site/0c9b82e7-d5e8-4583-80ac-b26ef6e62c7e" # ADD HERE YOUR URL
    headers:
    - name: Content-Type
      value: application/json
  template.app-sync-succeeded: |
    webhook:
      webhook-site:
        method: POST
        body: |
          {
            "content": ":white_check_mark: - {{.context.myUsername}} synced their application successfully! \n:rocket: -  URL: {{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}",
            "username": "ArgoCD",
            "avatar_url": "https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png"
          }
